version: "3"
services:
  nginx:
    image: nginx:1.22.1
    container_name: nginx
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "80:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - "./conf.d:/etc/nginx/conf.d"
      - "../dist:/usr/share/nginx/html"
      - "/var/log/nginx/emptyblog:/var/log/nginx/"
